import type { ProjectsData } from "@/_lib/types";

export const projectsWebdev: ProjectsData = {
  name: "projectsWD",
  description: "Web Development Projects by MGSimard",
  author: "MGSimard - https://github.com/MGSimard/",
  data: [
    {
      section: "Standalone",
      more: "https://github.com/MGSimard/",
      projects: [
        {
          title: "MGS RECS",
          thumbnail: "./assets/wd-thumbnails/thumb_mgs-recs.webp",
          features: ["Feature 1", "Feature 2", "Feature 3"],
          type: "Frontend Development",
          stack: "TanStack Start, TypeScript, Tailwind CSS",
          author: "MGSimard",
          description: "This is a description of the project",
          link: "https://mgs-recs.netlify.app/",
          githubRepo: "https://github.com/MGSimard/mgs-recs/",
        },
        {
          title: "SimDraft",
          thumbnail: "./assets/wd-thumbnails/thumb_simdraft.webp",
          features: ["Feature 1", "Feature 2", "Feature 3"],
          type: "Frontend Development",
          stack: "React, TypeScript, Zustand",
          author: "MGSimard",
          description: "This is a description of the project",
          link: "https://simdraft.pages.dev/",
          githubRepo: "https://github.com/MGSimard/simdraft/",
        },
        {
          title: "Myth War Archive v2",
          thumbnail: "./assets/wd-thumbnails/thumb_mwarchive_2.webp",
          features: ["Feature 1", "Feature 2", "Feature 3"],
          type: "Frontend Development",
          stack: "React, TypeScript",
          author: "MGSimard",
          description: "This is a description of the project",
          link: "https://mwarchive.pages.dev/",
          githubRepo: "https://github.com/MGSimard/myth-war-archive-v2/",
        },
        {
          title: "MDPVSS",
          thumbnail: "./assets/wd-thumbnails/thumb_mdpvss.webp",
          features: ["Feature 1", "Feature 2", "Feature 3"],
          type: "Frontend Development",
          stack: "React, TypeScript, Shiki, Zustand",
          author: "MGSimard",
          description: "This is a description of the project",
          link: "https://mdpvss.pages.dev/",
          githubRepo: "https://github.com/MGSimard/mdpvss/",
        },
        {
          title: "Sonata",
          thumbnail: "./assets/wd-thumbnails/thumb_sonata.webp",
          features: ["Feature 1", "Feature 2", "Feature 3"],
          type: "Frontend Development",
          stack: "React, TypeScript, Tone.js",
          author: "MGSimard",
          description: "This is a description of the project",
          link: "https://sonata.pages.dev/",
          githubRepo: "https://github.com/MGSimard/sonata/",
        },
        {
          title: "Emerald",
          thumbnail: "./assets/wd-thumbnails/thumb_emerald.webp",
          features: ["Feature 1", "Feature 2", "Feature 3"],
          type: "Frontend Development",
          stack: "React, TypeScript, Dexie.js",
          author: "MGSimard",
          description: "This is a description of the project",
          link: "https://emerald-app.pages.dev/",
          githubRepo: "https://github.com/MGSimard/emerald/",
        },
        {
          title: "NextGen",
          thumbnail: "./assets/wd-thumbnails/thumb_nextgen.webp",
          features: ["Feature 1", "Feature 2", "Feature 3"],
          type: "Fullstack Development",
          stack: "Personal Next.js Stack & Template",
          author: "MGSimard",
          description: "This is a description of the project",
          link: "https://nextgen-template.vercel.app/",
          githubRepo: "https://github.com/MGSimard/nextgen-template/",
        },
        {
          title: "VertexBlog",
          thumbnail: "./assets/wd-thumbnails/thumb_vertexblog.webp",
          features: ["Feature 1", "Feature 2", "Feature 3"],
          type: "Fullstack Development",
          stack: "Next.js, TypeScript, Drizzle (PostgreSQL), Lucia",
          author: "MGSimard",
          description: "This is a description of the project",
          link: "https://vertexblog.vercel.app/",
          githubRepo: "https://github.com/MGSimard/vertexblog/",
        },
        {
          title: "VertexDB",
          thumbnail: "./assets/wd-thumbnails/thumb_vertexdb.webp",
          features: ["Feature 1", "Feature 2", "Feature 3"],
          type: "Fullstack Development",
          stack: "Next.js, TypeScript, Drizzle (PostgreSQL), Clerk",
          author: "MGSimard",
          description: "This is a description of the project",
          link: "https://vertexdb.vercel.app/",
          githubRepo: "https://github.com/MGSimard/vertexdb/",
        },
        {
          title: "WuwaTools",
          thumbnail: "./assets/wd-thumbnails/thumb_wuwatools.webp",
          features: ["Feature 1", "Feature 2", "Feature 3"],
          type: "Frontend Development",
          stack: "React, TypeScript",
          author: "MGSimard",
          description: "This is a description of the project",
          link: "https://wuwatools.web.app/",
          githubRepo: "https://github.com/MGSimard/WuwaTools/",
        },
        {
          title: "LoLMH.Next",
          thumbnail: "./assets/wd-thumbnails/thumb_leaguemh.webp",
          features: ["Feature 1", "Feature 2", "Feature 3"],
          type: "Frontend Development",
          stack: "Next.js, TypeScript, React/JS Migration",
          author: "MGSimard",
          description: "This is a description of the project",
          link: "https://leaguemh-next.vercel.app/",
          githubRepo: "https://github.com/MGSimard/leaguemh-next/",
        },
        {
          title: "Myth War Archive (Legacy)",
          thumbnail: "./assets/wd-thumbnails/thumb_mwarchive.webp",
          features: ["Feature 1", "Feature 2", "Feature 3"],
          type: "Frontend Development",
          stack: "Next.js, TypeScript",
          author: "MGSimard",
          description: "This is a description of the project",
          link: "https://mwarchive.vercel.app/",
          githubRepo: "https://github.com/MGSimard/Myth-War-Archive/",
        },
        {
          title: "RoK Site Template",
          thumbnail: "./assets/wd-thumbnails/thumb_kdsite.webp",
          features: ["Feature 1", "Feature 2", "Feature 3"],
          type: "Frontend Development",
          stack: "React, TypeScript",
          author: "MGSimard",
          description: "This is a description of the project",
          link: "https://rok-kdsite.web.app/",
          githubRepo: "https://github.com/MGSimard/RoK-KDSite-Template/",
        },
      ],
    },
    {
      section: "Joint Projects",
      more: "",
      projects: [
        {
          title: "Rogue",
          thumbnail: "./assets/wd-thumbnails/thumb_rogue.webp",
          features: ["Feature 1", "Feature 2", "Feature 3"],
          type: "Fullstack Development",
          stack: "Wordpress, Divi",
          author: "MGSimard",
          description: "This is a description of the project",
          link: "https://rogue.no/",
          githubRepo: "",
        },
      ],
    },
    {
      section: "Frontend Mentor",
      more: "https://www.frontendmentor.io/profile/MGSimard/",
      projects: [
        {
          title: "Ecommerce Product Page",
          thumbnail: "./assets/wd-thumbnails/thumb_ecommerce.webp",
          features: ["Feature 1", "Feature 2", "Feature 3"],
          type: "Frontend Development",
          stack: "Vanilla",
          author: "MGSimard",
          description: "This is a description of the project",
          link: "https://mgsimard.github.io/frontendmentor/ecommerce-product-page/index.html",
          githubRepo: "",
        },
        {
          title: "Age Calculator App",
          thumbnail: "./assets/wd-thumbnails/thumb_agecalc.webp",
          features: ["Feature 1", "Feature 2", "Feature 3"],
          type: "Frontend Development",
          stack: "Vanilla",
          author: "MGSimard",
          description: "This is a description of the project",
          link: "https://mgsimard.github.io/frontendmentor/age-calculator-app/index.html",
          githubRepo: "",
        },
        {
          title: "Newsletter Sign-Up Form",
          thumbnail: "./assets/wd-thumbnails/thumb_newsletter.webp",
          features: ["Feature 1", "Feature 2", "Feature 3"],
          type: "Frontend Development",
          stack: "Vanilla",
          author: "MGSimard",
          description: "This is a description of the project",
          link: "https://mgsimard.github.io/frontendmentor/newsletter-sign-up-with-success-message/index.html",
          githubRepo: "",
        },
        {
          title: "FAQ Accordion Card",
          thumbnail: "./assets/wd-thumbnails/thumb_faq.webp",
          features: ["Feature 1", "Feature 2", "Feature 3"],
          type: "Frontend Development",
          stack: "Vanilla",
          author: "MGSimard",
          description: "This is a description of the project",
          link: "https://mgsimard.github.io/frontendmentor/faq-accordion-card/index.html",
          githubRepo: "",
        },
        {
          title: "Interactive Rating Component",
          thumbnail: "./assets/wd-thumbnails/thumb_rating.webp",
          features: ["Feature 1", "Feature 2", "Feature 3"],
          type: "Frontend Development",
          stack: "Vanilla",
          author: "MGSimard",
          description: "This is a description of the project",
          link: "https://mgsimard.github.io/frontendmentor/interactive-rating-component/index.html",
          githubRepo: "",
        },
        {
          title: "Interactive Card Details Form",
          thumbnail: "./assets/wd-thumbnails/thumb_credit.webp",
          features: ["Feature 1", "Feature 2", "Feature 3"],
          type: "Frontend Development",
          stack: "Vanilla, imask.js",
          author: "MGSimard",
          description: "This is a description of the project",
          link: "https://mgsimard.github.io/frontendmentor/interactive-card-details-form/index.html",
          githubRepo: "",
        },
        {
          title: "Notifications Page",
          thumbnail: "./assets/wd-thumbnails/thumb_notifications.webp",
          features: ["Feature 1", "Feature 2", "Feature 3"],
          type: "Frontend Development",
          stack: "Vanilla",
          author: "MGSimard",
          description: "This is a description of the project",
          link: "https://mgsimard.github.io/frontendmentor/notifications-page/index.html",
          githubRepo: "",
        },
        {
          title: "Results Summary Component",
          thumbnail: "./assets/wd-thumbnails/thumb_results.webp",
          features: ["Feature 1", "Feature 2", "Feature 3"],
          type: "Frontend Development",
          stack: "Vanilla",
          author: "MGSimard",
          description: "This is a description of the project",
          link: "https://mgsimard.github.io/frontendmentor/results-summary-component/index.html",
          githubRepo: "",
        },
        {
          title: "Profile Card Component",
          thumbnail: "./assets/wd-thumbnails/thumb_profile.webp",
          features: ["Feature 1", "Feature 2", "Feature 3"],
          type: "Frontend Development",
          stack: "Vanilla",
          author: "MGSimard",
          description: "This is a description of the project",
          link: "https://mgsimard.github.io/frontendmentor/profile-card-component/index.html",
          githubRepo: "",
        },
        {
          title: "News Homepage",
          thumbnail: "./assets/wd-thumbnails/thumb_news.webp",
          features: ["Feature 1", "Feature 2", "Feature 3"],
          type: "Frontend Development",
          stack: "Vanilla",
          author: "MGSimard",
          description: "This is a description of the project",
          link: "https://mgsimard.github.io/frontendmentor/news-homepage/index.html",
          githubRepo: "",
        },
        {
          title: "NFT Preview Card Component",
          thumbnail: "./assets/wd-thumbnails/thumb_nft.webp",
          features: ["Feature 1", "Feature 2", "Feature 3"],
          type: "Frontend Development",
          stack: "Vanilla",
          author: "MGSimard",
          description: "This is a description of the project",
          link: "https://mgsimard.github.io/frontendmentor/nft-preview-card-component/index.html",
          githubRepo: "",
        },
        {
          title: "Product Preview Card Component",
          thumbnail: "./assets/wd-thumbnails/thumb_product.webp",
          features: ["Feature 1", "Feature 2", "Feature 3"],
          type: "Frontend Development",
          stack: "Vanilla",
          author: "MGSimard",
          description: "This is a description of the project",
          link: "https://mgsimard.github.io/frontendmentor/product-preview-card-component/index.html",
          githubRepo: "",
        },
      ],
    },
    {
      section: "freeCodeCamp",
      more: "https://www.freecodecamp.org/MGSimard/",
      projects: [
        {
          title: "Pokémon Search App",
          thumbnail: "./assets/wd-thumbnails/thumb_pokemon.webp",
          features: ["Feature 1", "Feature 2", "Feature 3"],
          type: "Frontend Development",
          stack: "Vanilla",
          author: "MGSimard",
          description: "This is a description of the project",
          link: "https://mgsimard.github.io/freecodecamp/build-a-pokemon-search-app/index.html",
          githubRepo: "",
        },
        {
          title: "Video Game Sales",
          thumbnail: "./assets/wd-thumbnails/thumb_gamesales.webp",
          features: ["Feature 1", "Feature 2", "Feature 3"],
          type: "Frontend Development",
          stack: "Vanilla, D3.js",
          author: "MGSimard",
          description: "This is a description of the project",
          link: "https://codepen.io/MGSimard/full/OJBLBjd",
          githubRepo: "",
        },
        {
          title: "Cloropleth Map",
          thumbnail: "./assets/wd-thumbnails/thumb_cloropleth.webp",
          features: ["Feature 1", "Feature 2", "Feature 3"],
          type: "Frontend Development",
          stack: "Vanilla, D3.js",
          author: "MGSimard",
          description: "This is a description of the project",
          link: "https://codepen.io/MGSimard/full/QWZLwRP",
          githubRepo: "",
        },
        {
          title: "Heat Map",
          thumbnail: "./assets/wd-thumbnails/thumb_heatmap.webp",
          features: ["Feature 1", "Feature 2", "Feature 3"],
          type: "Frontend Development",
          stack: "Vanilla, D3.js",
          author: "MGSimard",
          description: "This is a description of the project",
          link: "https://codepen.io/MGSimard/full/rNZXOer",
          githubRepo: "",
        },
        {
          title: "Javascript Calculator",
          thumbnail: "./assets/wd-thumbnails/thumb_calculator.webp",
          features: ["Feature 1", "Feature 2", "Feature 3"],
          type: "Frontend Development",
          stack: "React",
          author: "MGSimard",
          description: "This is a description of the project",
          link: "https://codepen.io/MGSimard/full/ExeMZbN",
          githubRepo: "",
        },
        {
          title: "Markdown Previewer",
          thumbnail: "./assets/wd-thumbnails/thumb_markdown.webp",
          features: ["Feature 1", "Feature 2", "Feature 3"],
          type: "Frontend Development",
          stack: "React",
          author: "MGSimard",
          description: "This is a description of the project",
          link: "https://codepen.io/MGSimard/full/poOGqPP",
          githubRepo: "",
        },
        {
          title: "Random Quote Machine",
          thumbnail: "./assets/wd-thumbnails/thumb_quote.webp",
          features: ["Feature 1", "Feature 2", "Feature 3"],
          type: "Frontend Development",
          stack: "React",
          author: "MGSimard",
          description: "This is a description of the project",
          link: "https://codepen.io/MGSimard/full/abaXyrx",
          githubRepo: "",
        },
        {
          title: "Pomodoro Clock",
          thumbnail: "./assets/wd-thumbnails/thumb_pomodoro.webp",
          features: ["Feature 1", "Feature 2", "Feature 3"],
          type: "Frontend Development",
          stack: "React",
          author: "MGSimard",
          description: "This is a description of the project",
          link: "https://codepen.io/MGSimard/full/PodgjXd",
          githubRepo: "",
        },
        {
          title: "Personal Portfolio",
          thumbnail: "./assets/wd-thumbnails/thumb_portfolio.webp",
          features: ["Feature 1", "Feature 2", "Feature 3"],
          type: "Frontend Development",
          stack: "Vanilla",
          author: "MGSimard",
          description: "This is a description of the project",
          link: "https://mgsimard.github.io/freecodecamp/personal-portfolio-page/index.html",
          githubRepo: "",
        },
        {
          title: "Sign-Up Form",
          thumbnail: "./assets/wd-thumbnails/thumb_form.webp",
          features: ["Feature 1", "Feature 2", "Feature 3"],
          type: "Frontend Development",
          stack: "Vanilla",
          author: "MGSimard",
          description: "This is a description of the project",
          link: "https://mgsimard.github.io/freecodecamp/survey-form/index.html",
          githubRepo: "",
        },
        {
          title: "Documentation Page",
          thumbnail: "./assets/wd-thumbnails/thumb_docs.webp",
          features: ["Feature 1", "Feature 2", "Feature 3"],
          type: "Frontend Development",
          stack: "Vanilla",
          author: "MGSimard",
          description: "This is a description of the project",
          link: "https://mgsimard.github.io/freecodecamp/technical-documentation-page/index.html",
          githubRepo: "",
        },
        {
          title: "Character Page",
          thumbnail: "./assets/wd-thumbnails/thumb_tribute.webp",
          features: ["Feature 1", "Feature 2", "Feature 3"],
          type: "Frontend Development",
          stack: "Vanilla",
          author: "MGSimard",
          description: "This is a description of the project",
          link: "https://mgsimard.github.io/freecodecamp/tribute-page/index.html",
          githubRepo: "",
        },
      ],
    },
  ],
};
