import type { ProjectsData } from "@/_lib/types";

export const projectsWebdev: ProjectsData = {
  name: "projectsWD",
  description: "Web Development Projects by MGSimard",
  author: "MGSimard - https://github.com/MGSimard/",
  data: [
    {
      section: "Standalone",
      more: "https://github.com/MGSimard/",
      projects: [
        {
          title: "MGS RECS",
          thumbnail: "./assets/wd-thumbnails/thumb_mgs-recs.webp",
          features: ["In-Depth Recommendations", "Bleeding Edge Stacks", "Creative Coverage"],
          label: "Frontend Development",
          stack: "TanStack Start, TypeScript, Tailwind CSS",
          author: "MGSimard",
          description:
            "A collection of my personal and favorite recommentations all things web development encompassing the entire creative & technical spectrum. The hero is a canvas shader & atlas method borrowed from Clerk's website.",
          link: "https://mgs-recs.netlify.app/",
          githubRepo: "https://github.com/MGSimard/mgs-recs/",
        },
        {
          title: "SimDraft",
          thumbnail: "./assets/wd-thumbnails/thumb_simdraft.webp",
          features: ["Complete Drafting Simulation", "Always Up to Date", "Importing & Exporting"],
          label: "Frontend Development",
          stack: "React, TypeScript, Zustand",
          author: "MGSimard",
          description: `A fully functional recreation of League of Legends' drafting process meant as a tool for draft preparation and simulation. Includes the ban phase, pick phase, pick swapping, overrides, undo & redo, and draft importing & exporting as JSON files.

#### Disclaimer
SimDraft is not endorsed by Riot Games and does not reflect the views or opinions of Riot Games or anyone officially involved in producing or managing Riot Games properties. Riot Games and all associated properties are trademarks or registered trademarks of Riot Games, Inc.

All Riot-owned IP & assets (except manual SVG reproductions of PNGs) were procured through CommunityDragon following Riot Games' "Legal Jibber Jabber".`,
          link: "https://simdraft.pages.dev/",
          githubRepo: "https://github.com/MGSimard/simdraft/",
        },
        {
          title: "Myth War Archive v2",
          thumbnail: "./assets/wd-thumbnails/thumb_mwarchive_2.webp",
          features: ["Game History, World & Lore", "Guides", "Assets, Tools & Resources"],
          label: "Frontend Development",
          stack: "React, TypeScript",
          author: "MGSimard",
          description:
            "Preservation & utility project for the Myth War community. Myth War Archive is your go-to resource for everything related to Myth War Online and Myth War II. Whether you're a long-time fan or just discovering the games, this site is dedicated to preserving their legacy and supporting the communities that keep them alive.",
          link: "https://mwarchive.pages.dev/",
          githubRepo: "https://github.com/MGSimard/myth-war-archive-v2/",
        },
        {
          title: "MDPVSS",
          thumbnail: "./assets/wd-thumbnails/thumb_mdpvss.webp",
          features: ["Markdown Previewing", "Code Screenshotting", "Modifiable Styling"],
          label: "Frontend Development",
          stack: "React, TypeScript, Shiki, Zustand",
          author: "MGSimard",
          description:
            "A markdown previewing & screenshotting tool in the style of Cyberpunk 2077 UI design. Created due to similar tools like ray.so not having a rendered markdown option.",
          link: "https://mdpvss.pages.dev/",
          githubRepo: "https://github.com/MGSimard/mdpvss/",
        },
        {
          title: "Sonata",
          thumbnail: "./assets/wd-thumbnails/thumb_sonata.webp",
          features: ["Interactive Virtual Piano", "Transposition Controls", "3D-like interface"],
          label: "Frontend Development",
          stack: "React, TypeScript, Tone.js",
          author: "MGSimard",
          description: "Sonata — a simple, elegant, and accessible piano app. Built with the Web Audio API & Tone.js.",
          link: "https://sonata.pages.dev/",
          githubRepo: "https://github.com/MGSimard/sonata/",
        },
        {
          title: "Emerald",
          thumbnail: "./assets/wd-thumbnails/thumb_emerald.webp",
          features: ["Progress Tracking", "Local-First", "English & French"],
          label: "Frontend Development",
          stack: "React, TypeScript, Dexie.js",
          author: "MGSimard",
          description:
            "Emerald is an application local-first meant for tracking & managed progress of capturing wanted NPCs in Dofus.",
          link: "https://emerald-app.pages.dev/",
          githubRepo: "https://github.com/MGSimard/emerald/",
        },
        {
          title: "NextGen",
          thumbnail: "./assets/wd-thumbnails/thumb_nextgen.webp",
          features: ["Fullstack Next.js Development"],
          label: "Fullstack Development",
          stack: "Personal Next.js Stack & Template",
          author: "MGSimard",
          description:
            "Prior to switching my stack to TanStack Start, NextGen's main purpose was for quickstarting my own personal projects with a bleeding edge stack. It does not include payment-related utilites, testing libraries, UI libraries or Tailwind CSS.",
          link: "https://nextgen-template.vercel.app/",
          githubRepo: "https://github.com/MGSimard/nextgen-template/",
        },
        {
          title: "VertexBlog",
          thumbnail: "./assets/wd-thumbnails/thumb_vertexblog.webp",
          features: ["Multi-User Blogging Environment", "Windows 95 User Interface", "Virtualized Listing"],
          label: "Fullstack Development",
          stack: "Next.js, TypeScript, Drizzle (PostgreSQL), Lucia",
          author: "MGSimard",
          description:
            "My second Next.js application. VertexBlog is a blogging platform based on the Windows 95 user interface. It runs as a file explorer directory where blogs are set up as folders within /Documents, and posts are text files within their respective blogs.",
          link: "https://vertexblog.vercel.app/",
          githubRepo: "https://github.com/MGSimard/vertexblog/",
        },
        {
          title: "VertexDB",
          thumbnail: "./assets/wd-thumbnails/thumb_vertexdb.webp",
          features: ["Video Game Resource Directory", "Public Voting & Resources Submission", "RBAC & Admin Dashboard"],
          label: "Fullstack Development",
          stack: "Next.js, TypeScript, Drizzle (PostgreSQL), Clerk",
          author: "MGSimard",
          description:
            "First ever Next.js application. VertexDB would serve as a publicly voted-on directory of resources tied to video games, harnessing IGDB as its video game database. Users can submit resources for any given video game on the platform, and others can vote on them. Submissions can be reported and moderated through an RBAC-gated administration dashboard to review reports.",
          link: "https://vertexdb.vercel.app/",
          githubRepo: "https://github.com/MGSimard/vertexdb/",
        },
        {
          title: "WuwaTools",
          thumbnail: "./assets/wd-thumbnails/thumb_wuwatools.webp",
          features: ["Character Roster", "Tier List Creator", "Interactive World Map"],
          label: "Frontend Development",
          stack: "React, TypeScript",
          author: "MGSimard",
          description: `This project was an excuse to learn the basics of TypeScript, naturally I end up spending more time wrangling with unrelated stuff like Drag & Drop. Bounced from library to library, settled for the alpha rewrite of dnd-kit by Clauderic. Following his documentation, refactor took about 10 minutes tops, pretty baller library rewrite.

The major problem writing this application was that there was no public API for Wuthering Waves, so I had to write the entire JSON data myself (without keys it's about 70k characters by now). Bit of a nightmare, without mentioning maintaining all of it between updates.`,
          link: "https://wuwatools.web.app/",
          githubRepo: "https://github.com/MGSimard/WuwaTools/",
        },
        {
          title: "LoLMH.Next",
          thumbnail: "./assets/wd-thumbnails/thumb_leaguemh.webp",
          features: ["Match History Fetching", "Dynamic CDN Asset Fetching", "LoL Branding Guidelines"],
          label: "Frontend Development",
          stack: "Next.js, TypeScript, React/JS Migration",
          author: "MGSimard",
          description:
            "A recreation of my vanilla LoLCBL project, minus the CBL part, in React. Its only purpose is to fetch match histories of players across all League of Legends regions with public APIs. This project acted as practice with React, queries, and dynamic CDN asset fetching. It is no longer functional as I am not actively rotating development API keys from Riot Games.",
          link: "https://leaguemh-next.vercel.app/",
          githubRepo: "https://github.com/MGSimard/leaguemh-next/",
        },
        {
          title: "Myth War Archive (Legacy)",
          thumbnail: "./assets/wd-thumbnails/thumb_mwarchive.webp",
          features: ["Game History, World & Lore", "Guides", "Assets, Tools & Resources"],
          label: "Frontend Development",
          stack: "Next.js, TypeScript",
          author: "MGSimard",
          description: "Legacy version of Myth War Archive.",
          link: "https://mwarchive.vercel.app/",
          githubRepo: "https://github.com/MGSimard/Myth-War-Archive/",
        },
        {
          title: "RoK Site Template",
          thumbnail: "./assets/wd-thumbnails/thumb_kdsite.webp",
          features: ["Landing Page", "KVK Player Statistics", "Google Sheets API Integration"],
          label: "Frontend Development",
          stack: "React, TypeScript",
          author: "MGSimard",
          description:
            "A template for a Rise of Kingdoms community websites. Used as a replacement for a blogspot website our Kingdom used at the time of me playing RoK a while back.",
          link: "https://rok-kdsite.web.app/",
          githubRepo: "https://github.com/MGSimard/RoK-KDSite-Template/",
        },
      ],
    },
    {
      section: "Joint Projects",
      more: "",
      projects: [
        {
          title: "Rogue",
          thumbnail: "./assets/wd-thumbnails/thumb_rogue.webp",
          features: ["Landing Page", "Wordpress & Divi CMS", "SEO, CDN, etc."],
          label: "Fullstack Development",
          stack: "Wordpress, Divi",
          author: "MGSimard, Rogue",
          description:
            "Website built for a Norwegian Cybersecurity solutions company, in tandem with the company's founder. Visited multiple options but ultimately landed on Wordpress & Divi in order for the owner to have the ability to participate & own the website.",
          link: "https://rogue.no/",
        },
      ],
    },
    {
      section: "Frontend Mentor",
      more: "https://www.frontendmentor.io/profile/MGSimard/",
      projects: [
        {
          title: "Ecommerce Product Page",
          thumbnail: "./assets/wd-thumbnails/thumb_ecommerce.webp",
          features: ["Product Page", "Cart Functionality", "Lightbox Gallery"],
          label: "Frontend Development",
          stack: "Vanilla",
          author: "MGSimard",
          description: "Early-stage Frontend Mentor challenge.",
          link: "https://mgsimard.github.io/frontendmentor/ecommerce-product-page/index.html",
        },
        {
          title: "Age Calculator App",
          thumbnail: "./assets/wd-thumbnails/thumb_agecalc.webp",
          features: ["Age Calculator", "Input Validation"],
          label: "Frontend Development",
          stack: "Vanilla",
          author: "MGSimard",
          description: "Early-stage Frontend Mentor challenge.",
          link: "https://mgsimard.github.io/frontendmentor/age-calculator-app/index.html",
        },
        {
          title: "Newsletter Sign-Up Form",
          thumbnail: "./assets/wd-thumbnails/thumb_newsletter.webp",
          features: ["Form"],
          label: "Frontend Development",
          stack: "Vanilla",
          author: "MGSimard",
          description: "Early-stage Frontend Mentor challenge.",
          link: "https://mgsimard.github.io/frontendmentor/newsletter-sign-up-with-success-message/index.html",
        },
        {
          title: "FAQ Accordion Card",
          thumbnail: "./assets/wd-thumbnails/thumb_faq.webp",
          features: ["JS-less Interactivity"],
          label: "Frontend Development",
          stack: "Vanilla",
          author: "MGSimard",
          description: "Early-stage Frontend Mentor challenge.",
          link: "https://mgsimard.github.io/frontendmentor/faq-accordion-card/index.html",
        },
        {
          title: "Interactive Rating Component",
          thumbnail: "./assets/wd-thumbnails/thumb_rating.webp",
          features: ["Form"],
          label: "Frontend Development",
          stack: "Vanilla",
          author: "MGSimard",
          description: "Early-stage Frontend Mentor challenge.",
          link: "https://mgsimard.github.io/frontendmentor/interactive-rating-component/index.html",
        },
        {
          title: "Interactive Card Details Form",
          thumbnail: "./assets/wd-thumbnails/thumb_credit.webp",
          features: ["Form"],
          label: "Frontend Development",
          stack: "Vanilla, imask.js",
          author: "MGSimard",
          description: "Early-stage Frontend Mentor challenge.",
          link: "https://mgsimard.github.io/frontendmentor/interactive-card-details-form/index.html",
        },
        {
          title: "Notifications Page",
          thumbnail: "./assets/wd-thumbnails/thumb_notifications.webp",
          features: ["Notification Page"],
          label: "Frontend Development",
          stack: "Vanilla",
          author: "MGSimard",
          description: "Early-stage Frontend Mentor challenge.",
          link: "https://mgsimard.github.io/frontendmentor/notifications-page/index.html",
        },
        {
          title: "Results Summary Component",
          thumbnail: "./assets/wd-thumbnails/thumb_results.webp",
          features: ["Results Summary Component"],
          label: "Frontend Development",
          stack: "Vanilla",
          author: "MGSimard",
          description: "Early-stage Frontend Mentor challenge.",
          link: "https://mgsimard.github.io/frontendmentor/results-summary-component/index.html",
        },
        {
          title: "Profile Card Component",
          thumbnail: "./assets/wd-thumbnails/thumb_profile.webp",
          features: ["Profile Card Component"],
          label: "Frontend Development",
          stack: "Vanilla",
          author: "MGSimard",
          description: "Early-stage Frontend Mentor challenge.",
          link: "https://mgsimard.github.io/frontendmentor/profile-card-component/index.html",
        },
        {
          title: "News Homepage",
          thumbnail: "./assets/wd-thumbnails/thumb_news.webp",
          features: ["Grid Layout"],
          label: "Frontend Development",
          stack: "Vanilla",
          author: "MGSimard",
          description: "Early-stage Frontend Mentor challenge.",
          link: "https://mgsimard.github.io/frontendmentor/news-homepage/index.html",
        },
        {
          title: "NFT Preview Card Component",
          thumbnail: "./assets/wd-thumbnails/thumb_nft.webp",
          features: ["It's a thing"],
          label: "Frontend Development",
          stack: "Vanilla",
          author: "MGSimard",
          description: "Early-stage Frontend Mentor challenge.",
          link: "https://mgsimard.github.io/frontendmentor/nft-preview-card-component/index.html",
        },
        {
          title: "Product Preview Card Component",
          thumbnail: "./assets/wd-thumbnails/thumb_product.webp",
          features: ["Product Preview Card"],
          label: "Frontend Development",
          stack: "Vanilla",
          author: "MGSimard",
          description: "Early-stage Frontend Mentor challenge.",
          link: "https://mgsimard.github.io/frontendmentor/product-preview-card-component/index.html",
        },
      ],
    },
    {
      section: "freeCodeCamp",
      more: "https://www.freecodecamp.org/MGSimard/",
      projects: [
        {
          title: "Pokémon Search App",
          thumbnail: "./assets/wd-thumbnails/thumb_pokemon.webp",
          features: ["Data Fetching", "Styled UI"],
          label: "Frontend Development",
          stack: "Vanilla",
          author: "MGSimard",
          description: "Early-stage freeCodeCamp challenge.",
          link: "https://mgsimard.github.io/freecodecamp/build-a-pokemon-search-app/index.html",
        },
        {
          title: "Video Game Sales",
          thumbnail: "./assets/wd-thumbnails/thumb_gamesales.webp",
          features: ["Data Visualization"],
          label: "Frontend Development",
          stack: "Vanilla, D3.js",
          author: "MGSimard",
          description: "Early-stage freeCodeCamp challenge.",
          link: "https://codepen.io/MGSimard/full/OJBLBjd",
        },
        {
          title: "Cloropleth Map",
          thumbnail: "./assets/wd-thumbnails/thumb_cloropleth.webp",
          features: ["Data Visualization"],
          label: "Frontend Development",
          stack: "Vanilla, D3.js",
          author: "MGSimard",
          description: "Early-stage freeCodeCamp challenge.",
          link: "https://codepen.io/MGSimard/full/QWZLwRP",
        },
        {
          title: "Heat Map",
          thumbnail: "./assets/wd-thumbnails/thumb_heatmap.webp",
          features: ["Data Visualization"],
          label: "Frontend Development",
          stack: "Vanilla, D3.js",
          author: "MGSimard",
          description: "Early-stage freeCodeCamp challenge.",
          link: "https://codepen.io/MGSimard/full/rNZXOer",
        },
        {
          title: "Javascript Calculator",
          thumbnail: "./assets/wd-thumbnails/thumb_calculator.webp",
          features: ["Calculator"],
          label: "Frontend Development",
          stack: "React",
          author: "MGSimard",
          description: "Early-stage freeCodeCamp challenge.",
          link: "https://codepen.io/MGSimard/full/ExeMZbN",
        },
        {
          title: "Markdown Previewer",
          thumbnail: "./assets/wd-thumbnails/thumb_markdown.webp",
          features: ["Markdown Previewing"],
          label: "Frontend Development",
          stack: "React",
          author: "MGSimard",
          description: "Early-stage freeCodeCamp challenge.",
          link: "https://codepen.io/MGSimard/full/poOGqPP",
        },
        {
          title: "Random Quote Machine",
          thumbnail: "./assets/wd-thumbnails/thumb_quote.webp",
          features: ["Random Quote Machine"],
          label: "Frontend Development",
          stack: "React",
          author: "MGSimard",
          description: "Early-stage freeCodeCamp challenge.",
          link: "https://codepen.io/MGSimard/full/abaXyrx",
        },
        {
          title: "Pomodoro Clock",
          thumbnail: "./assets/wd-thumbnails/thumb_pomodoro.webp",
          features: ["Pomodoro Clock"],
          label: "Frontend Development",
          stack: "React",
          author: "MGSimard",
          description: "Early-stage freeCodeCamp challenge.",
          link: "https://codepen.io/MGSimard/full/PodgjXd",
        },
        {
          title: "Personal Portfolio",
          thumbnail: "./assets/wd-thumbnails/thumb_portfolio.webp",
          features: ["Personal Portfolio"],
          label: "Frontend Development",
          stack: "Vanilla",
          author: "MGSimard",
          description: "Early-stage freeCodeCamp challenge.",
          link: "https://mgsimard.github.io/freecodecamp/personal-portfolio-page/index.html",
        },
        {
          title: "Sign-Up Form",
          thumbnail: "./assets/wd-thumbnails/thumb_form.webp",
          features: ["Sign-Up Form"],
          label: "Frontend Development",
          stack: "Vanilla",
          author: "MGSimard",
          description: "Early-stage freeCodeCamp challenge.",
          link: "https://mgsimard.github.io/freecodecamp/survey-form/index.html",
        },
        {
          title: "Documentation Page",
          thumbnail: "./assets/wd-thumbnails/thumb_docs.webp",
          features: ["Documentation"],
          label: "Frontend Development",
          stack: "Vanilla",
          author: "MGSimard",
          description: "Early-stage freeCodeCamp challenge.",
          link: "https://mgsimard.github.io/freecodecamp/technical-documentation-page/index.html",
        },
        {
          title: "Character Page",
          thumbnail: "./assets/wd-thumbnails/thumb_tribute.webp",
          features: ["Character Sheet"],
          label: "Frontend Development",
          stack: "Vanilla",
          author: "MGSimard",
          description: "Early-stage freeCodeCamp challenge.",
          link: "https://mgsimard.github.io/freecodecamp/tribute-page/index.html",
        },
      ],
    },
  ],
};
