import type { ProjectsData } from "@/_lib/types";

export const projectsWebdev: ProjectsData = {
  name: "projectsWD",
  description: "Web Development Projects by MGSimard",
  author: "MGSimard - https://github.com/MGSimard/",
  data: [
    {
      section: "Standalone",
      more: "https://github.com/MGSimard/",
      projects: [
        {
          title: "Portfolio V4",
          thumbnail: "./assets/wd-thumbnails/thumb_portfolio_v4.webp",
          label: "Frontend Development",
          carouselImages: [],
          overview: "The latest (for now) iteration of my personal portfolio website.",
          features: ["Web Development", "Game Development", "Cyberpunk 2077 UI"],
          stack: "TanStack Start, TypeScript, Tailwind CSS, Base UI",
          description: `Felt the need to revamp my portfolio website, rebuilt entirely in the style of Cyberpunk 2077's User Interface design. You're currently viewing it.`,
          link: null,
          githubRepo: null,
        },
        {
          title: "MGS RECS",
          thumbnail: "./assets/wd-thumbnails/thumb_mgs-recs.webp",
          label: "Frontend Development",
          carouselImages: [],
          overview:
            "A collection of my personal and favorite recommendations all things web development encompassing the entire creative & technical spectrum.",
          features: ["In-Depth Recommendations", "Bleeding Edge Stacks", "Helpful Guidance"],
          stack: "TanStack Start, TypeScript, Tailwind CSS",
          description: `From the creative & design process to the more technical aspects of web development, MGS RECS is a compilation of tooling I've personally used and recommend for different stages of development, skill & use cases.
          
Over 20 different categories are covered, including code editors, frontend & fullstack frameworks, UI libraries, database solutions, authentication, CI/CD & version control, design tools etc.

The hero is a canvas shader & texture atlas method borrowed from Clerk's website, reverse-engineered from the website's compiled JavaScript bundle.`,
          link: "https://mgs-recs.netlify.app/",
          githubRepo: "https://github.com/MGSimard/mgs-recs/",
        },
        {
          title: "SimDraft",
          thumbnail: "./assets/wd-thumbnails/thumb_simdraft.webp",
          label: "Frontend Development",
          carouselImages: [],
          overview: "A League of Legends drafting simulation tool for practice & strategy planning.",
          features: ["Complete Drafting Simulation", "Always Up to Date", "Importing & Exporting"],
          stack: "React, TypeScript, Zustand",
          description: `A fully functional recreation of League of Legends' drafting process meant as a tool for draft preparation and simulation. Includes the ban phase, pick phase, pick swapping, overrides, undo & redo, and draft importing & exporting as JSON files. This project acted as a test with giving more agency to AI (Claude 4.5) in regards to application logic and state management.
          
The overall design & functionality of the application were directly inspired by Riot Games' official branding guidelines & in-client UI.`,
          link: "https://simdraft.pages.dev/",
          githubRepo: "https://github.com/MGSimard/simdraft/",
        },
        {
          title: "Myth War Archive v2",
          thumbnail: "./assets/wd-thumbnails/thumb_mwarchive_2.webp",
          label: "Frontend Development",
          carouselImages: [],
          overview: "Community resource hub for the old Myth War games.",
          features: ["Game History, World & Lore", "Guides", "Assets, Tools & Resources"],
          stack: "React, TypeScript",
          description:
            "Preservation & utility project for the Myth War community. Myth War Archive is a go-to resource for everything related to Myth War Online and Myth War II. Whether you're a long-time fan or just discovering the games, this site is dedicated to preserving their legacy and supporting the communities that keep them alive.",
          link: "https://mwarchive.pages.dev/",
          githubRepo: "https://github.com/MGSimard/myth-war-archive-v2/",
        },
        {
          title: "MDPVSS",
          thumbnail: "./assets/wd-thumbnails/thumb_mdpvss.webp",
          label: "Frontend Development",
          carouselImages: [],
          overview: "Markdown preview and screenshot tool with styled Cyberpunk 2077 UI.",
          features: ["Markdown Previewing", "Code Screenshotting", "Modifiable Styling"],
          stack: "React, TypeScript, Shiki, Zustand",
          description:
            "A markdown previewing & screenshotting tool in the style of Cyberpunk 2077 UI design. Created due to similar tools like ray.so not having a rendered markdown option.",
          link: "https://mdpvss.pages.dev/",
          githubRepo: "https://github.com/MGSimard/mdpvss/",
        },
        {
          title: "Sonata",
          thumbnail: "./assets/wd-thumbnails/thumb_sonata.webp",
          label: "Frontend Development",
          carouselImages: [],
          overview: "A dynamic virtual piano web app built with Tone.js.",
          features: ["Interactive Virtual Piano", "Transposition Controls", "3D-like interface"],
          stack: "React, TypeScript, Tone.js",
          description: `Sonata is a simple, elegant, and accessible piano app built on top of Tone.js. The user interface, like the piano itself, was written manually in pure vanilla CSS & JavaScript. The piano supports transposition to allow playing a wide range of different music, as well as volume controls & dynamic key playing and note history visuals.
            
The sound library itself was created using a modified derivative of a reFX Nexus piano pack, extracted as individual notes from FL Studio.

And for the record, [yes I do actually play on a computer keyboard](https://www.youtube.com/watch?v=ZCXBoQYOq6s) _(12 years ago)_. Still do from time to time.`,
          link: "https://sonata.pages.dev/",
          githubRepo: "https://github.com/MGSimard/sonata/",
        },
        {
          title: "Emerald",
          thumbnail: "./assets/wd-thumbnails/thumb_emerald.webp",
          label: "Frontend Development",
          carouselImages: [],
          overview:
            "Emerald is a local-first application for tracking & managing the capture progress of wanted NPCs in Dofus.",
          features: ["Progress Tracking", "Local-First", "English & French"],
          stack: "React, TypeScript, Dexie.js",
          description:
            "Emerald is a local-first web app meant for tracking & managed progress of capturing wanted NPCs in Dofus. The user interface follows Dofus' core branding & UI styles, and contains image assets for each of the capturable NPCs in the game. Progress is tracked locally in the browser's IndexedDB database using Dexie.js, and is consistently validated against the app's database schema.",
          link: "https://emerald-app.pages.dev/",
          githubRepo: "https://github.com/MGSimard/emerald/",
        },
        {
          title: "NextGen",
          thumbnail: "./assets/wd-thumbnails/thumb_nextgen.webp",
          label: "Fullstack Development",
          carouselImages: [],
          overview: "Deprecated starter template for personal Next.js projects.",
          features: ["Fullstack Next.js Development", "Better Auth", "PostgreSQL & Drizzle ORM"],
          stack: "Personal Next.js Stack & Template",
          description:
            "Prior to switching my stack to TanStack Start, NextGen's main purpose was for quickstarting my own personal projects with a bleeding edge stack. It does not include payment-related utilites, testing libraries, UI libraries or Tailwind CSS.",
          link: "https://nextgen-template.vercel.app/",
          githubRepo: "https://github.com/MGSimard/nextgen-template/",
        },
        {
          title: "VertexBlog",
          thumbnail: "./assets/wd-thumbnails/thumb_vertexblog.webp",
          label: "Fullstack Development",
          carouselImages: [],
          overview: "A multi-user blogging platform based on the Windows 95 user interface.",
          features: ["Multi-User Blogging Environment", "Windows 95 User Interface", "Virtualized Listing"],
          stack: "Next.js, TypeScript, Drizzle (PostgreSQL), Lucia",
          description:
            "My second Next.js application. VertexBlog is a blogging platform based on the Windows 95 user interface. It runs as a file explorer directory where blogs are set up as folders within /Documents, and posts are text files within their respective blogs.",
          link: "https://vertexblog.vercel.app/",
          githubRepo: "https://github.com/MGSimard/vertexblog/",
        },
        {
          title: "VertexDB",
          thumbnail: "./assets/wd-thumbnails/thumb_vertexdb.webp",
          label: "Fullstack Development",
          carouselImages: [],
          overview: "Community-powered video game resource directory built on top of the IGDB API.",
          features: ["Video Game Resource Directory", "Public Voting & Resources Submission", "RBAC & Admin Dashboard"],
          stack: "Next.js, TypeScript, Drizzle (PostgreSQL), Clerk",
          description: `First ever Next.js application. VertexDB would serve as a publicly voted-on directory of resources tied to video games, harnessing IGDB as its video game database. Users can submit resources for any given video game on the platform, and others can vote on them. Submissions can be reported and moderated through an RBAC-gated administration dashboard to review reports.
            
This project is not currently functional as I am not actively rotating development API keys from IGDB.`,
          link: "https://vertexdb.vercel.app/",
          githubRepo: "https://github.com/MGSimard/vertexdb/",
        },
        {
          title: "WuwaTools",
          thumbnail: "./assets/wd-thumbnails/thumb_wuwatools.webp",
          label: "Frontend Development",
          carouselImages: [],
          overview:
            "Toolset for Wuthering Waves, containing a character roster, tier list creator & an interactive world map.",
          features: ["Character Roster", "Tier List Creator", "Interactive World Map"],
          stack: "React, TypeScript",
          description: `This project was an excuse to learn the basics of TypeScript, naturally I end up spending more time wrangling with unrelated stuff like Drag & Drop. Bounced from library to library, settled for the alpha rewrite of dnd-kit by Clauderic. Following his documentation, refactor took about 10 minutes tops, pretty baller library rewrite.

The major problem writing this application was that there was no public API for Wuthering Waves, so I had to write the entire JSON data myself (without keys it's about 70k characters by now). Bit of a nightmare, without mentioning maintaining all of it between updates.`,
          link: "https://wuwatools.web.app/",
          githubRepo: "https://github.com/MGSimard/WuwaTools/",
        },
        {
          title: "LoLMH.Next",
          thumbnail: "./assets/wd-thumbnails/thumb_leaguemh.webp",
          label: "Frontend Development",
          carouselImages: [],
          overview: "League of Legends summoner profile & match history searching tool.",
          features: ["Match History Fetching", "Dynamic CDN Asset Fetching", "LoL Branding Guidelines"],
          stack: "Next.js, TypeScript, React/JS Migration",
          description:
            "A recreation of my vanilla LoLCBL project, minus the CBL part, in React. Its only purpose is to fetch match histories of players across all League of Legends regions with public APIs. This project acted as practice with React, queries, and dynamic CDN asset fetching. It is no longer functional as I am not actively rotating development API keys from Riot Games.",
          link: "https://leaguemh-next.vercel.app/",
          githubRepo: "https://github.com/MGSimard/leaguemh-next/",
        },
        {
          title: "Myth War Archive (Legacy)",
          thumbnail: "./assets/wd-thumbnails/thumb_mwarchive.webp",
          label: "Frontend Development",
          carouselImages: [],
          overview: "The original, legacy version of Myth War Archive.",
          features: ["Game History, World & Lore", "Guides", "Assets, Tools & Resources"],
          stack: "Next.js, TypeScript",
          description:
            "The original, legacy version of Myth War Archive. This project was the first iteration of the Myth War Archive, and was the basis for the current version.",
          link: "https://mwarchive.vercel.app/",
          githubRepo: "https://github.com/MGSimard/Myth-War-Archive/",
        },
        {
          title: "RoK Site Template",
          thumbnail: "./assets/wd-thumbnails/thumb_kdsite.webp",
          label: "Frontend Development",
          carouselImages: [],
          overview: "Template for Rise of Kingdoms community sites.",
          features: ["Landing Page", "KVK Player Statistics", "Google Sheets API Integration"],
          stack: "React, TypeScript",
          description:
            "A template for a Rise of Kingdoms community websites. Used as a replacement for a blogspot website our Kingdom used at the time of me playing RoK a while back. Its purpose is to provide a simple, clean & responsive landing page for a Kingdom, as well as a player statistics page using Google Sheets with SheetDB.io.",
          link: "https://rok-kdsite.web.app/",
          githubRepo: "https://github.com/MGSimard/RoK-KDSite-Template/",
        },
      ],
    },
    {
      section: "Joint Projects",
      more: "",
      projects: [
        {
          title: "Rogue",
          thumbnail: "./assets/wd-thumbnails/thumb_rogue.webp",
          label: "Fullstack Development",
          carouselImages: [],
          overview: "Website built for Rogue Cybersecurity AS.",
          features: ["Landing Pages", "Wordpress & Divi CMS", "SEO, CDN, etc."],
          stack: "Wordpress, Divi, Bunny CDN",
          description: `Website built for a Norwegian Cybersecurity solutions company in tandem with the company's founder. Visited multiple stack options and ultimately landed on Wordpress & Divi in order for the owner to have the ability to participate & own the website. Went through multiple design iterations, designed logos & iconography, set up SEO, CDN, mailing etc.
            
For the record: Wordpress & Divi suck. Never again.`,
          link: "https://rogue.no/",
          githubRepo: null,
        },
      ],
    },
    {
      section: "Frontend Mentor",
      more: "https://www.frontendmentor.io/profile/MGSimard/",
      projects: [
        {
          title: "Ecommerce Product Page",
          thumbnail: "./assets/wd-thumbnails/thumb_ecommerce.webp",
          label: "Frontend Development",
          carouselImages: [],
          overview:
            "An Ecommerce Product page built with Vanilla HTML, CSS & JavaScript. The product preview opens as a lightbox gallery, and there's a working cart functionality.",
          features: ["Product Page", "Cart Functionality", "Lightbox Gallery"],
          stack: "Vanilla",
          description: "Early-stage Frontend Mentor challenge, following the supplied design specs.",
          link: "https://mgsimard.github.io/frontendmentor/ecommerce-product-page/index.html",
          githubRepo: null,
        },
        {
          title: "Age Calculator App",
          thumbnail: "./assets/wd-thumbnails/thumb_agecalc.webp",
          label: "Frontend Development",
          carouselImages: [],
          overview:
            "An application for calculating the age of a person in years, months & days based on their birth date.",
          features: ["Age Calculator", "Input Validation"],
          stack: "Vanilla",
          description: "Early-stage Frontend Mentor challenge, following the supplied design specs.",
          link: "https://mgsimard.github.io/frontendmentor/age-calculator-app/index.html",
          githubRepo: null,
        },
        {
          title: "Newsletter Sign-Up Form",
          thumbnail: "./assets/wd-thumbnails/thumb_newsletter.webp",
          label: "Frontend Development",
          carouselImages: [],
          overview: "A newsletter sign-up form with a success message, contains basic form validation.",
          features: ["Form", "Input Validation"],
          stack: "Vanilla",
          description: "Early-stage Frontend Mentor challenge, following the supplied design specs.",
          link: "https://mgsimard.github.io/frontendmentor/newsletter-sign-up-with-success-message/index.html",
          githubRepo: null,
        },
        {
          title: "FAQ Accordion Card",
          thumbnail: "./assets/wd-thumbnails/thumb_faq.webp",
          label: "Frontend Development",
          carouselImages: [],
          overview:
            "An FAQ accordion card with a JS-less hover interactions, leverages the HTML details & summary API.",
          features: ["JS-less Interactivity", "HTML Details & Summary API"],
          stack: "Vanilla",
          description: "Early-stage Frontend Mentor challenge, following the supplied design specs.",
          link: "https://mgsimard.github.io/frontendmentor/faq-accordion-card/index.html",
          githubRepo: null,
        },
        {
          title: "Interactive Rating Component",
          thumbnail: "./assets/wd-thumbnails/thumb_rating.webp",
          label: "Frontend Development",
          carouselImages: [],
          overview: "An interactive rating component with a dynamic rating UI, contains basic form validation.",
          features: ["Form"],
          stack: "Vanilla",
          description: "Early-stage Frontend Mentor challenge, following the supplied design specs.",
          link: "https://mgsimard.github.io/frontendmentor/interactive-rating-component/index.html",
          githubRepo: null,
        },
        {
          title: "Interactive Card Details Form",
          thumbnail: "./assets/wd-thumbnails/thumb_credit.webp",
          label: "Frontend Development",
          carouselImages: [],
          overview:
            "An interactive card details form with a input UI mirroring, contains basic form validation and uses imask.js.",
          features: ["Form", "Input Validation", "Card Input Mirroring"],
          stack: "Vanilla, imask.js",
          description: "Early-stage Frontend Mentor challenge, following the supplied design specs.",
          link: "https://mgsimard.github.io/frontendmentor/interactive-card-details-form/index.html",
          githubRepo: null,
        },
        {
          title: "Notifications Page",
          thumbnail: "./assets/wd-thumbnails/thumb_notifications.webp",
          label: "Frontend Development",
          carouselImages: [],
          overview: "A notifications page with a dynamic notification badge.",
          features: ["Notification Page", "Notification Count Badge"],
          stack: "Vanilla",
          description: "Early-stage Frontend Mentor challenge, following the supplied design specs.",
          link: "https://mgsimard.github.io/frontendmentor/notifications-page/index.html",
          githubRepo: null,
        },
        {
          title: "Results Summary Component",
          thumbnail: "./assets/wd-thumbnails/thumb_results.webp",
          label: "Frontend Development",
          carouselImages: [],
          overview: "Basic UI for a scoring results summary.",
          features: ["Results Summary Component"],
          stack: "Vanilla",
          description: "Early-stage Frontend Mentor challenge, following the supplied design specs.",
          link: "https://mgsimard.github.io/frontendmentor/results-summary-component/index.html",
          githubRepo: null,
        },
        {
          title: "Profile Card Component",
          thumbnail: "./assets/wd-thumbnails/thumb_profile.webp",
          label: "Frontend Development",
          carouselImages: [],
          overview: "Generic profile card component.",
          features: ["Profile Card Component"],
          stack: "Vanilla",
          description: "Early-stage Frontend Mentor challenge, following the supplied design specs.",
          link: "https://mgsimard.github.io/frontendmentor/profile-card-component/index.html",
          githubRepo: null,
        },
        {
          title: "News Homepage",
          thumbnail: "./assets/wd-thumbnails/thumb_news.webp",
          label: "Frontend Development",
          carouselImages: [],
          overview: "A news homepage with a grid layout, fully responsive & mobile-friendly.",
          features: ["Grid Layout", "Responsive Design"],
          stack: "Vanilla",
          description: "Early-stage Frontend Mentor challenge, following the supplied design specs.",
          link: "https://mgsimard.github.io/frontendmentor/news-homepage/index.html",
          githubRepo: null,
        },
        {
          title: "NFT Preview Card Component",
          thumbnail: "./assets/wd-thumbnails/thumb_nft.webp",
          label: "Frontend Development",
          carouselImages: [],
          overview: "A NFT preview card component with a basic hover effect.",
          features: ["NFT Preview Card"],
          stack: "Vanilla",
          description: "Early-stage Frontend Mentor challenge, following the supplied design specs.",
          link: "https://mgsimard.github.io/frontendmentor/nft-preview-card-component/index.html",
          githubRepo: null,
        },
        {
          title: "Product Preview Card Component",
          thumbnail: "./assets/wd-thumbnails/thumb_product.webp",
          label: "Frontend Development",
          carouselImages: [],
          overview: "Designer product preview card component.",
          features: ["Product Preview Card"],
          stack: "Vanilla",
          description: "Early-stage Frontend Mentor challenge, following the supplied design specs.",
          link: "https://mgsimard.github.io/frontendmentor/product-preview-card-component/index.html",
          githubRepo: null,
        },
      ],
    },
    {
      section: "freeCodeCamp",
      more: "https://www.freecodecamp.org/MGSimard/",
      projects: [
        {
          title: "Pokémon Search App",
          thumbnail: "./assets/wd-thumbnails/thumb_pokemon.webp",
          label: "Frontend Development",
          carouselImages: [],
          overview: "Course project: A Pokémon search app with a styled UI & data fetching.",
          features: ["Data Fetching", "Styled UI"],
          stack: "Vanilla",
          description: "Early-stage freeCodeCamp challenge, following the supplied technical requirements.",
          link: "https://mgsimard.github.io/freecodecamp/build-a-pokemon-search-app/index.html",
          githubRepo: null,
        },
        {
          title: "Video Game Sales",
          thumbnail: "./assets/wd-thumbnails/thumb_gamesales.webp",
          label: "Frontend Development",
          carouselImages: [],
          overview: "Course project: A video game sales data visualization using D3.js.",
          features: ["Data Visualization"],
          stack: "Vanilla, D3.js",
          description: "Early-stage freeCodeCamp challenge, following the supplied technical requirements.",
          link: "https://codepen.io/MGSimard/full/OJBLBjd",
          githubRepo: null,
        },
        {
          title: "Cloropleth Map",
          thumbnail: "./assets/wd-thumbnails/thumb_cloropleth.webp",
          label: "Frontend Development",
          carouselImages: [],
          overview:
            "Course project: A chloropleth map of Bachelor's degrees holders or higher in the United States, built with D3.js.",
          features: ["Data Visualization"],
          stack: "Vanilla, D3.js",
          description: "Early-stage freeCodeCamp challenge, following the supplied technical requirements.",
          link: "https://codepen.io/MGSimard/full/QWZLwRP",
          githubRepo: null,
        },
        {
          title: "Heat Map",
          thumbnail: "./assets/wd-thumbnails/thumb_heatmap.webp",
          label: "Frontend Development",
          carouselImages: [],
          overview: "Course project: A heat map of global land-surface temperatures over time since 1753, using D3.js.",
          features: ["Data Visualization"],
          stack: "Vanilla, D3.js",
          description: "Early-stage freeCodeCamp challenge, following the supplied technical requirements.",
          link: "https://codepen.io/MGSimard/full/rNZXOer",
          githubRepo: null,
        },
        {
          title: "Javascript Calculator",
          thumbnail: "./assets/wd-thumbnails/thumb_calculator.webp",
          label: "Frontend Development",
          carouselImages: [],
          overview: "Course project: A calculator built with React, allowing for basic arithmetic operations.",
          features: ["Calculator"],
          stack: "React",
          description: "Early-stage freeCodeCamp challenge, following the supplied technical requirements.",
          link: "https://codepen.io/MGSimard/full/ExeMZbN",
          githubRepo: null,
        },
        {
          title: "Markdown Previewer",
          thumbnail: "./assets/wd-thumbnails/thumb_markdown.webp",
          label: "Frontend Development",
          carouselImages: [],
          overview: "Course project: A markdown previewer built with React.",
          features: ["Markdown Previewing"],
          stack: "React",
          description: "Early-stage freeCodeCamp challenge, following the supplied technical requirements.",
          link: "https://codepen.io/MGSimard/full/poOGqPP",
          githubRepo: null,
        },
        {
          title: "Random Quote Machine",
          thumbnail: "./assets/wd-thumbnails/thumb_quote.webp",
          label: "Frontend Development",
          carouselImages: [],
          overview: "Course project: A random quote machine built with React.",
          features: ["Random Quote Machine"],
          stack: "React",
          description: "Early-stage freeCodeCamp challenge, following the supplied technical requirements.",
          link: "https://codepen.io/MGSimard/full/abaXyrx",
          githubRepo: null,
        },
        {
          title: "Pomodoro Clock",
          thumbnail: "./assets/wd-thumbnails/thumb_pomodoro.webp",
          label: "Frontend Development",
          carouselImages: [],
          overview: "Course project: A pomodoro clock, allows setting session & break periods.",
          features: ["Pomodoro Clock"],
          stack: "React",
          description: "Early-stage freeCodeCamp challenge, following the supplied technical requirements.",
          link: "https://codepen.io/MGSimard/full/PodgjXd",
          githubRepo: null,
        },
        {
          title: "Personal Portfolio",
          thumbnail: "./assets/wd-thumbnails/thumb_portfolio.webp",
          label: "Frontend Development",
          carouselImages: [],
          overview: "Course project: A personal portfolio page built with Vanilla HTML, CSS & JavaScript.",
          features: ["Personal Portfolio"],
          stack: "Vanilla",
          description: "Early-stage freeCodeCamp challenge, following the supplied technical requirements.",
          link: "https://mgsimard.github.io/freecodecamp/personal-portfolio-page/index.html",
          githubRepo: null,
        },
        {
          title: "Sign-Up Form",
          thumbnail: "./assets/wd-thumbnails/thumb_form.webp",
          label: "Frontend Development",
          carouselImages: [],
          overview: "Course project: A video game account sign-up form.",
          features: ["Sign-Up Form", "Input Validation"],
          stack: "Vanilla",
          description: "Early-stage freeCodeCamp challenge, following the supplied technical requirements.",
          link: "https://mgsimard.github.io/freecodecamp/survey-form/index.html",
          githubRepo: null,
        },
        {
          title: "Documentation Page",
          thumbnail: "./assets/wd-thumbnails/thumb_docs.webp",
          label: "Frontend Development",
          carouselImages: [],
          overview:
            "Course project: A documentation page built around Myth War Online, which would eventually become the two different versions of my Myth War Archive project.",
          features: ["Documentation"],
          stack: "Vanilla",
          description: "Early-stage freeCodeCamp challenge, following the supplied technical requirements.",
          link: "https://mgsimard.github.io/freecodecamp/technical-documentation-page/index.html",
          githubRepo: null,
        },
        {
          title: "Character Page",
          thumbnail: "./assets/wd-thumbnails/thumb_tribute.webp",
          label: "Frontend Development",
          carouselImages: [],
          overview: "A class/character sheet preview for Myth War Online.",
          features: ["Character Sheet"],
          stack: "Vanilla",
          description: "Early-stage freeCodeCamp challenge, following the supplied technical requirements.",
          link: "https://mgsimard.github.io/freecodecamp/tribute-page/index.html",
          githubRepo: null,
        },
      ],
    },
  ],
};
