/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebdevRouteImport } from './routes/webdev'
import { Route as GamedevRouteImport } from './routes/gamedev'
import { Route as IndexRouteImport } from './routes/index'

const WebdevRoute = WebdevRouteImport.update({
  id: '/webdev',
  path: '/webdev',
  getParentRoute: () => rootRouteImport,
} as any)
const GamedevRoute = GamedevRouteImport.update({
  id: '/gamedev',
  path: '/gamedev',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gamedev': typeof GamedevRoute
  '/webdev': typeof WebdevRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gamedev': typeof GamedevRoute
  '/webdev': typeof WebdevRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gamedev': typeof GamedevRoute
  '/webdev': typeof WebdevRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/gamedev' | '/webdev'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/gamedev' | '/webdev'
  id: '__root__' | '/' | '/gamedev' | '/webdev'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GamedevRoute: typeof GamedevRoute
  WebdevRoute: typeof WebdevRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/webdev': {
      id: '/webdev'
      path: '/webdev'
      fullPath: '/webdev'
      preLoaderRoute: typeof WebdevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gamedev': {
      id: '/gamedev'
      path: '/gamedev'
      fullPath: '/gamedev'
      preLoaderRoute: typeof GamedevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GamedevRoute: GamedevRoute,
  WebdevRoute: WebdevRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
